### ISSUE TITLE
Want to add a resource to reading.md 

### ISSUE THREAD

**Issue by Genesis3800** [eth-protocol-fellows/cohort-four#11]
Hey guys,

let me know if this is not the correct way to propose this, but I want to add this Ethereum yellow paper walkthrough to the reading list.
Let me know if I can create a PR with this?
[https://www.youtube.com/watch?v=e84V1MxRlYs](https://www.youtube.com/watch?v=e84V1MxRlYs)

**Comment by taxmeifyoucan** [comment]
This is a great resource, please feel free to just open a PR and continue the discussion there. 

The whole repository is opened to collaboration so you can propose resources you find useful and missing there. Thanks!
