### ISSUE TITLE
Office Hours #8: Last of project presentation 

### ISSUE THREAD

**Issue by taxmeifyoucan** [eth-protocol-fellows/cohort-four#324]
# Meeting info

This call will be the last opportunity to present your project at Office Hours. If you didn't have a chance to present yet, comment on this issue to add your presentation to the agenda. 

- [Sep 12, 2023, 15:00 UTC](https://savvytime.com/converter/utc-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-australia-sydney/sep-12-2023/3pm)
- Duration: 90 minutes 
- Meeting link: https://meet.ethereum.org/epf-office-hours

# Agenda 

 - Add your presentation to agenda by commenting here 
 - Moved from the previous call: 
   - @weiihann

**Comment by T-ess** [comment]
I'd like to present

**Comment by v4lproik** [comment]
I'd like to present too

**Comment by agnxsh** [comment]
I'd like to present although Advaita had led our project's presentation few weeks ago, do i need to present @taxmeifyoucan in that case? Cuz I'll be presenting on the same topic essentially.

**Comment by anshalshukla** [comment]
I'd like to present too

**Comment by taxmeifyoucan** [comment]
@agnxsh No need to present here since Advaita already covered it. But if you want to elaborate on your project, feel free to record a video presentation and share it

**Comment by dragan2234** [comment]
I'd like to present my project

**Comment by chirag-bgh** [comment]
I would like to present.

**Comment by agnxsh** [comment]
> @agnxsh No need to present here since Advaita already covered it. But if you want to elaborate on your project, feel free to record a video presentation and share it 

Yes I'll do that then.

**Comment by atkinsonholly** [comment]
I'd like to present

**Comment by AdedamolaXL** [comment]
I would like to present, ideally after Holly, since our projects are very similar :)

**Comment by danielrachi** [comment]
I'd like to present my new project :)

Maybe I should go last, since this would be my second time presenting.

**Comment by radkomih** [comment]
I'd like to present (even though the proposal is still draft)

**Comment by 0x3114** [comment]
Putting myself out there on the list just in case I make it 👀 will go last. Otherwise happy to make a video. Manav's presentation content will likely overlap with mine so might be quick.

**Comment by 0x3114** [comment]
> I'd like to present my project

Manav - would it make sense to combine presentations?

**Comment by taxmeifyoucan** [comment]
Current schedule: 
- @weiihann
- @manav2401 + @0x3114 
- @T-ess 
- @v4lproik 
- @dragan2234 
- @atkinsonholly + @AdedamolaXL 
- @radkomih 
- @danielrachi

**Comment by anshalshukla** [comment]
@taxmeifyoucan I and @manav2401  are planning to present together since I am also working on the same project. Please add me there in the slot with him. @0x3114 Can add to it if she is available, I can see her asking for the last slot above.
