### ISSUE TITLE
Need R & D disord link.

### ISSUE THREAD

**Issue by HyperDanisH** [eth-protocol-fellows/cohort-four#333]
Hi everyone,
I am someone who is interested in EPF program, but from the looks of it the applications of this program has unfortunately been ended. Fortunately though, it says that the program is completely open, So I would love to have link to the discord server of R & D ethereum. I would appericiate if someone could answer my 2 questions aswell, first, can I pick an project and start working on it right now? Second, Where can I get all the links to the programs material.
 
Thanks for reading,

**Comment by taxmeifyoucan** [comment]
Hey, to answer your questions. The program is mid way through but it's fully open so you can always tag along. In this phase, I would recommend dedicating your time to learning, studying what fellows are working and figuring out what parts of the ecosystem you are interested in. You can use this knowledge and improve your baseline for applying to future cohorts. 
Regarding materials, everything is in this repo - the program guide and all work reported by fellows. 
Link to R&D discord https://discord.gg/3pCDEpNk
