### ISSUE TITLE
Office Hours #9: AMA w/ Marius and lightclient

### ISSUE THREAD

**Issue by taxmeifyoucan** [eth-protocol-fellows/cohort-four#357]
# Meeting info

After project presentations are over, we are hosting another AMA session at Office Hours call. This one will be joined by two developers from go-ethereum: @MariusVanDerWijden and @lightclient! Both are experts on execution layer and go but with great insight into many domains of the protocol. 

Make sure to prepare some insightful questions to seize the opportunity to learn from them.  

- [September 19, 2023, 15:00 UTC](https://savvytime.com/converter/utc-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-australia-sydney/sep-19-2023/3pm)
- Duration: 60 minutes 
- Meeting link: https://meet.ethereum.org/epf-office-hours

# Agenda 

- AMA with Marius van der Wijden and lightclient
  -  Prepare your questions regarding topics geth, fuzzing, execution layer, EVM, EIPs, JSON-RPC, Dencun upgrades, testing, pytests...

**Comment by lightclient** [comment]
![image](https://github.com/eth-protocol-fellows/cohort-four/assets/14004106/4cf1b3ef-6966-4691-b18b-2aaf18b3be6a)
