### ISSUE TITLE
Office Hours #16: Final project presentations

### ISSUE THREAD

**Issue by taxmeifyoucan** [eth-protocol-fellows/cohort-four#496]
# Meeting info

This is the very last Office Hours call. It will be dedicated to cohort wrap up and mainly closing project presentations by fellows who cannot making it to Istanbul. 

**If you are not coming to EPF Day during Devconnect, prepare a short presentation about your work during the cohort and current state of your project.** You can use your Final dev update for the presentation, share your summary like at a standup call. 

- [November 7, 2023, 15:00 UTC](https://savvytime.com/converter/utc-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-australia-sydney/nov-7-2023/3pm)
- Duration: 90 minutes 
- Meeting link: https://meet.ethereum.org/epf-office-hours

# Agenda 

- Short cohort retrospect and summary
- Closing presentations by fellows
  - Come to share summary of your project, its final state and your EPF experience 
  - Up to 10 minutes per fellow 
  - Sign up by adding comments below

**Comment by Godspower-Eze** [comment]
I will be presenting

**Comment by atkinsonholly** [comment]
I'll present

**Comment by manav2401** [comment]
I (and other people working on same project as me) will be presenting

**Comment by gzanitti** [comment]
I will be presenting too!

**Comment by galadd** [comment]
I'll present
