### ISSUE TITLE
Office Hours #2: Run a node

### ISSUE THREAD

**Issue by taxmeifyoucan** [eth-protocol-fellows/cohort-four#95]
# Meeting info

The third EPF Office Hours call will host a workshop on using Ethereum clients.

- [Jul 25, 2022, 15:00 UTC](https://savvytime.com/converter/utc-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-australia-sydney/jul-25-2023/3pm)
- Duration: 60 minutes 
- Meeting link: https://meet.ethereum.org/epf-office-hours

# Agenda 

- Intro and questions
- Workshop agenda https://notes.ethereum.org/@MarioHavel/nodes-workshop

**Comment by Godspower-Eze** [comment]
It would be great if touched on the Nimbus Client. Thank you!

**Comment by Ifechukwudaniel** [comment]
how can we get the recording of the workshop
